networks:
  loki:

services:
  loki:
    image: ghcr.io/garrettkyle/loki:1.0
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - $HOME/.ssh:/root/.ssh:ro
    networks:
      - loki

  promtail:
    image: ghcr.io/garrettkyle/promtail:1.0
    volumes:
      - /var/log:/var/log
      - $HOME/.ssh:/root/.ssh:ro
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

volumes:
  loki_data:
    driver: local