networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:

services:

  prometheus:
    image: 715788907281.dkr.ecr.ca-central-1.amazonaws.com/monitoring/prometheus:1.0
    container_name: prometheus
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - $HOME/.ssh:/root/.ssh:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  alertmanager:
    image: 715788907281.dkr.ecr.ca-central-1.amazonaws.com/monitoring/alertmanager:1.0
    container_name: alertmanager
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - $HOME/.ssh:/root/.ssh:ro
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager_config.yaml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - monitoring