global:
  resolve_timeout: 5m

route:
  group_by: ['alertname'] 
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'sns_alerts'

receivers:
  - name: 'sns_alerts'
    sns_configs:
      - api_url: 'https://sns.ca-central-1.amazonaws.com'
        topic_arn: 'arn:aws:sns:ca-central-1:715788907281:prometheus_alarms'
        sigv4:
          region: 'ca-central-1'
        message: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'
        subject: 'Prometheus Alert: {{ .CommonLabels.alertname }}'

# Optional: Configure alert silences
# silences:
#   - matchers:
#       - name: 'severity'
#         value: 'critical'
#     startsAt: '2024-11-05T00:00:00Z'
#     endsAt: '2024-11-05T12:00:00Z'