global:
  resolve_timeout: 5m

route:
  group_by: ['alertname'] 
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'null-receiver'

# Define a dummy receiver
receivers:
  - name: 'null-receiver'

# Optional: Configure alert silences
# silences:
#   - matchers:
#       - name: 'severity'
#         value: 'critical'
#     startsAt: '2024-11-05T00:00:00Z'
#     endsAt: '2024-11-05T12:00:00Z'