global:
  body_size_limit: 15MB
  evaluation_interval: 30s
  external_labels:
    foo: bar
  query_log_file: "/prometheus/prometheus_query.log"
  sample_limit: 0  # default aka unlimited
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "system_alerts.yaml"

# This functionality available as of version 3.x
scrape_config_files:
  - "scrape_config.yaml"

# remote_write is what you would use to save metrics to something like Thanos
#remote_write:

# OLTP is to enable integration with OpenTelemetry data sources
#otlp:

# remote_read is where you would specify external storage systems like Thanos
# and Prometheus would read them as if they were stored local to Prometheus
#remote_read:

# Allows out-of-order metrics (due to network delays etc) to be received
storage:
  tsdb:
    out_of_order_time_window: 30m

alerting:
  alertmanagers:
    - scheme: https
      api_version: v2
      path_prefix: /
      timeout: 10s
      static_configs:
        - targets:
            - "alertmanager:9093"