scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'prometheus'  # Add a label for the instance
          environment: 'dev'  # Add a label for the environment
          role: 'monitoring'  # Add a label for the role of the node